name: ut

permissions: read-all

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-in-zephyr-ci-container:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    container: ghcr.io/zephyrproject-rtos/ci:v0.27.4
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains

    strategy:
      matrix:
        board: [qemu_cortex_m3, native_sim, unit_testing]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize workspace
        run: |
          west init
          west update

      - name: List tests for ${{ matrix.board }}
        run: |
          west twister -v -p ${{ matrix.board }} --test-tree -T tests

      - name: Run Twister for ${{ matrix.board }}
        run: |
          west twister -v -p ${{ matrix.board }} -T tests

      - name: Save artifact
        uses: actions/upload-artifact@v4.6.0
        if: ${{ always() }}
        with:
          name: build_artifacts_${{ github.run_id }}_${{ matrix.board }}
          path: |
            twister-out/*
